# Cloud Run Configuration for Backend
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    name: learning-path-builder-backend
    annotations:
        run.googleapis.com/ingress: all
        run.googleapis.com/execution-environment: gen2
spec:
    template:
        metadata:
            annotations:
                autoscaling.knative.dev/maxScale: "10"
                autoscaling.knative.dev/minScale: "0"
                run.googleapis.com/cpu-throttling: "true"
                run.googleapis.com/execution-environment: gen2
        spec:
            containerConcurrency: 100
            timeoutSeconds: 300
            containers:
                - image: gcr.io/PROJECT_ID/learning-path-builder-backend:latest
                  ports:
                      - name: http1
                        containerPort: 3000
                  env:
                      - name: NODE_ENV
                        value: "production"
                      - name: PORT
                        value: "3000"
                      - name: FRONTEND_URL
                        value: "https://learning-path-builder-frontend-PROJECT_ID.a.run.app"
                  resources:
                      limits:
                          cpu: "1"
                          memory: "512Mi"
                      requests:
                          cpu: "0.5"
                          memory: "256Mi"
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 3000
                      initialDelaySeconds: 30
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 3000
                      initialDelaySeconds: 5
                      periodSeconds: 5
                      timeoutSeconds: 3
                      failureThreshold: 3
