# Cloud Run Configuration for FlashLearn AI Frontend
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: flashlearn-ai-frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '5'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 60
      containers:
        - image: gcr.io/PROJECT_ID/flashlearn-ai-frontend:latest
          ports:
            - name: http1
              containerPort: 80
           env:
             - name: VITE_API_URL
               value: 'https://flashlearn-ai-backend-PROJECT_ID.a.run.app/api'
             - name: FIREBASE_API_KEY
               valueFrom:
                 secretKeyRef:
                   name: firebase-config
                   key: api_key
             - name: FIREBASE_AUTH_DOMAIN
               valueFrom:
                 secretKeyRef:
                   name: firebase-config
                   key: auth_domain
             - name: FIREBASE_PROJECT_ID
               valueFrom:
                 secretKeyRef:
                   name: firebase-config
                   key: project_id
             - name: FIREBASE_STORAGE_BUCKET
               valueFrom:
                 secretKeyRef:
                   name: firebase-config
                   key: storage_bucket
             - name: FIREBASE_MESSAGING_SENDER_ID
               valueFrom:
                 secretKeyRef:
                   name: firebase-config
                   key: messaging_sender_id
             - name: FIREBASE_APP_ID
               valueFrom:
                 secretKeyRef:
                   name: firebase-config
                   key: app_id
             - name: FIREBASE_MEASUREMENT_ID
               valueFrom:
                 secretKeyRef:
                   name: firebase-config
                   key: measurement_id
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
            requests:
              cpu: '0.5'
              memory: '256Mi'
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
