# Cloud Run Configuration for Frontend
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    name: learning-path-builder-frontend
    annotations:
        run.googleapis.com/ingress: all
        run.googleapis.com/execution-environment: gen2
spec:
    template:
        metadata:
            annotations:
                autoscaling.knative.dev/maxScale: "5"
                autoscaling.knative.dev/minScale: "0"
                run.googleapis.com/cpu-throttling: "true"
                run.googleapis.com/execution-environment: gen2
        spec:
            containerConcurrency: 1000
            timeoutSeconds: 300
            containers:
                - image: gcr.io/PROJECT_ID/learning-path-builder-frontend:latest
                  ports:
                      - name: http1
                        containerPort: 80
                  env:
                      - name: VITE_API_URL
                        value: "https://learning-path-builder-backend-PROJECT_ID.a.run.app/api"
                  resources:
                      limits:
                          cpu: "1"
                          memory: "256Mi"
                      requests:
                          cpu: "0.5"
                          memory: "128Mi"
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 80
                      initialDelaySeconds: 30
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 80
                      initialDelaySeconds: 5
                      periodSeconds: 5
                      timeoutSeconds: 3
                      failureThreshold: 3
