"use client"

import { useState, useEffect } from "react"
import { useRouter, useParams } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { Brain, ArrowLeft, ChevronLeft, ChevronRight, RotateCw, CheckCircle2, Loader2 } from "lucide-react"
import { useAuth } from "@/lib/auth-context"
import { cn } from "@/lib/utils"
import { ValidationQuizDialog } from "@/components/validation-quiz-dialog"
import { FlashcardRating } from "@/components/flashcard-rating"
import { ModuleResources } from "@/components/module-resources"

// Mock flashcards - In production, these would be generated by AI
const mockFlashcards = [
  {
    id: "fc1",
    question: "Qu'est-ce que React ?",
    answer:
      "React est une bibliothèque JavaScript pour construire des interfaces utilisateur. Elle permet de créer des composants réutilisables et gère efficacement les mises à jour du DOM.",
  },
  {
    id: "fc2",
    question: "Qu'est-ce qu'un composant React ?",
    answer:
      "Un composant React est une fonction ou une classe qui retourne du JSX. Il encapsule la logique et l'interface utilisateur d'une partie de l'application.",
  },
  {
    id: "fc3",
    question: "Quelle est la différence entre props et state ?",
    answer:
      "Les props sont des données passées d'un composant parent à un composant enfant (immuables). Le state est un objet géré localement par le composant (mutable).",
  },
  {
    id: "fc4",
    question: "Qu'est-ce que le Virtual DOM ?",
    answer:
      "Le Virtual DOM est une représentation en mémoire du DOM réel. React l'utilise pour optimiser les mises à jour en calculant les différences avant de modifier le DOM réel.",
  },
  {
    id: "fc5",
    question: "Qu'est-ce que JSX ?",
    answer:
      "JSX est une extension de syntaxe JavaScript qui permet d'écrire du code ressemblant à du HTML dans JavaScript. Il est transformé en appels de fonctions React.",
  },
]

// Mock resources for the module
const mockResources = [
  {
    id: "r1",
    title: "Documentation officielle React",
    type: "documentation" as const,
    url: "https://react.dev",
    description: "La documentation complète et officielle de React avec des guides et références API",
  },
  {
    id: "r2",
    title: "Tutoriel interactif React",
    type: "tutorial" as const,
    url: "https://react.dev/learn",
    description: "Apprenez React étape par étape avec des exemples interactifs",
  },
  {
    id: "r3",
    title: "Les hooks React expliqués",
    type: "video" as const,
    url: "https://www.youtube.com/watch?v=example",
    description: "Une vidéo complète sur l'utilisation des hooks React",
  },
]

export default function StudyPage() {
  const { user } = useAuth()
  const router = useRouter()
  const params = useParams()
  const { objectiveId, pathId, moduleId } = params

  const [flashcards, setFlashcards] = useState<any[]>([])
  const [currentIndex, setCurrentIndex] = useState(0)
  const [isFlipped, setIsFlipped] = useState(false)
  const [studiedCards, setStudiedCards] = useState<Set<string>>(new Set())
  const [loading, setLoading] = useState(true)
  const [showQuizDialog, setShowQuizDialog] = useState(false)
  const [moduleTitle, setModuleTitle] = useState("Introduction à React")

  useEffect(() => {
    if (!user) {
      router.push("/login")
      return
    }

    // TODO: Fetch flashcards from Firestore
    setTimeout(() => {
      setFlashcards(mockFlashcards)
      setLoading(false)
    }, 1000)
  }, [user, router, objectiveId, pathId, moduleId])

  const currentCard = flashcards[currentIndex]
  const progress = (studiedCards.size / flashcards.length) * 100
  const allCardsStudied = studiedCards.size === flashcards.length

  const handleFlip = () => {
    setIsFlipped(!isFlipped)
    if (!isFlipped) {
      setStudiedCards(new Set(studiedCards).add(currentCard.id))
    }
  }

  const handleNext = () => {
    if (currentIndex < flashcards.length - 1) {
      setCurrentIndex(currentIndex + 1)
      setIsFlipped(false)
    }
  }

  const handlePrevious = () => {
    if (currentIndex > 0) {
      setCurrentIndex(currentIndex - 1)
      setIsFlipped(false)
    }
  }

  const handleFinishModule = () => {
    setShowQuizDialog(true)
  }

  const handleQuizComplete = (passed: boolean) => {
    setShowQuizDialog(false)
    if (passed) {
      router.push(`/paths/${objectiveId}`)
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-muted/20">
      {/* Header */}
      <header className="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button variant="ghost" size="icon" onClick={() => router.push(`/paths/${objectiveId}`)}>
                <ArrowLeft className="h-5 w-5" />
              </Button>
              <div className="flex items-center gap-2">
                <Brain className="h-6 w-6 text-primary" />
                <div>
                  <h1 className="font-semibold">{moduleTitle}</h1>
                  <p className="text-sm text-muted-foreground">
                    {currentIndex + 1} / {flashcards.length}
                  </p>
                </div>
              </div>
            </div>
            <div className="text-right">
              <div className="text-sm font-medium">{Math.round(progress)}%</div>
              <p className="text-xs text-muted-foreground">Progression</p>
            </div>
          </div>
          <Progress value={progress} className="mt-4" />
        </div>
      </header>

      <main className="container mx-auto px-4 py-8 max-w-4xl">
        {/* Flashcard */}
        <div className="mb-8">
          <div className="relative h-[400px] cursor-pointer perspective-1000" onClick={handleFlip}>
            <div
              className={cn(
                "absolute inset-0 transition-transform duration-500 transform-style-3d",
                isFlipped && "rotate-y-180",
              )}
            >
              {/* Front of card */}
              <Card className={cn("absolute inset-0 border-2 backface-hidden", !isFlipped && "z-10")}>
                <CardContent className="flex flex-col items-center justify-center h-full p-8 text-center">
                  <div className="mb-4 text-sm font-medium text-primary">Question</div>
                  <h2 className="text-2xl md:text-3xl font-bold text-balance leading-relaxed">
                    {currentCard.question}
                  </h2>
                  <div className="mt-8 flex items-center gap-2 text-sm text-muted-foreground">
                    <RotateCw className="h-4 w-4" />
                    <span>Cliquez pour voir la réponse</span>
                  </div>
                </CardContent>
              </Card>

              {/* Back of card */}
              <Card className={cn("absolute inset-0 border-2 backface-hidden rotate-y-180", isFlipped && "z-10")}>
                <CardContent className="flex flex-col items-center justify-center h-full p-8 text-center">
                  <div className="mb-4 text-sm font-medium text-green-500">Réponse</div>
                  <p className="text-lg md:text-xl leading-relaxed text-pretty">{currentCard.answer}</p>
                  <div className="mt-8 flex items-center gap-2 text-sm text-muted-foreground">
                    <RotateCw className="h-4 w-4" />
                    <span>Cliquez pour voir la question</span>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>

        {/* Rating component below flashcard */}
        <div className="mb-6">
          <FlashcardRating
            flashcardId={currentCard.id}
            onRatingChange={(rating, comment) => {
              console.log("[v0] Rating:", rating, "Comment:", comment)
              // TODO: Save to Firestore
            }}
          />
        </div>

        {/* Navigation */}
        <div className="flex items-center justify-between mb-6">
          <Button variant="outline" onClick={handlePrevious} disabled={currentIndex === 0}>
            <ChevronLeft className="h-4 w-4 mr-2" />
            Précédent
          </Button>

          <div className="flex items-center gap-2">
            {flashcards.map((card, index) => (
              <button
                key={card.id}
                onClick={() => {
                  setCurrentIndex(index)
                  setIsFlipped(false)
                }}
                className={cn(
                  "h-2 rounded-full transition-all",
                  index === currentIndex
                    ? "w-8 bg-primary"
                    : studiedCards.has(card.id)
                      ? "w-2 bg-primary/50"
                      : "w-2 bg-muted",
                )}
              />
            ))}
          </div>

          <Button variant="outline" onClick={handleNext} disabled={currentIndex === flashcards.length - 1}>
            Suivant
            <ChevronRight className="h-4 w-4 ml-2" />
          </Button>
        </div>

        {/* Resources section */}
        <div className="mb-6">
          <ModuleResources
            resources={mockResources}
            onSelfAssess={(resourceId) => {
              console.log("[v0] Self-assessed resource:", resourceId)
              // TODO: Save to Firestore
            }}
          />
        </div>

        {/* Completion Card */}
        {allCardsStudied && (
          <Card className="border-2 bg-gradient-to-br from-primary/5 to-primary/10">
            <CardContent className="p-8 text-center space-y-4">
              <CheckCircle2 className="h-12 w-12 text-green-500 mx-auto" />
              <h3 className="text-2xl font-bold">Module terminé !</h3>
              <p className="text-muted-foreground max-w-md mx-auto">
                Vous avez étudié toutes les flashcards. Passez le quiz de validation pour débloquer le module suivant.
              </p>
              <Button size="lg" onClick={handleFinishModule}>
                Passer le quiz de validation
              </Button>
            </CardContent>
          </Card>
        )}

        {/* Study Tips */}
        <Card className="mt-6 border-2">
          <CardContent className="p-6">
            <h3 className="font-semibold mb-3">Conseils d'étude</h3>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li className="flex items-start gap-2">
                <div className="h-1.5 w-1.5 rounded-full bg-primary mt-2 flex-shrink-0" />
                <span>Prenez le temps de bien comprendre chaque concept avant de passer au suivant</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="h-1.5 w-1.5 rounded-full bg-primary mt-2 flex-shrink-0" />
                <span>Révisez régulièrement les flashcards pour renforcer votre mémoire</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="h-1.5 w-1.5 rounded-full bg-primary mt-2 flex-shrink-0" />
                <span>N'hésitez pas à revenir sur les cartes que vous trouvez difficiles</span>
              </li>
            </ul>
          </CardContent>
        </Card>
      </main>

      <ValidationQuizDialog
        open={showQuizDialog}
        onOpenChange={setShowQuizDialog}
        onComplete={handleQuizComplete}
        moduleTitle={moduleTitle}
      />
    </div>
  )
}
