name: CI - Tests and Linting

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint backend
        run: |
          cd packages/backend
          npm run lint || echo "⚠️ Linting issues found"

      - name: Lint frontend
        run: |
          cd packages/frontend
          npm run lint || echo "⚠️ Linting issues found"

      - name: Test backend
        run: npm run test:ci --workspace=@flashlearn-ai/backend

      - name: Test frontend
        run: npm run test:ci --workspace=@flashlearn-ai/frontend

      - name: Build backend
        run: |
          cd packages/backend
          npm run build

      - name: Build frontend
        env:
          VITE_API_URL: http://localhost:3000/api
        run: |
          cd packages/frontend
          npm run build
